version: 2
formats: []

build:
  image: latest

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
<<<<<<< HEAD
        - docs
=======
        - docs
>>>>>>> 8f4201082eda9d3ef81478b309c7fa7ac05d23d5
